<?php

declare(strict_types=1);

final class SkeletonBootstrapSeedTest extends TransactionedTestCase
{
	public function testBootstrapSeedEnsuresAdminHomepageLoginAndCoreAdminPages(): void
	{
		$username = 'skeleton_seed_admin';
		$password = 'skeleton_seed_password';

		TestHelperEnvironment::setEnvironmentVariable('APP_BOOTSTRAP_ADMIN_USERNAME', $username);
		TestHelperEnvironment::setEnvironmentVariable('APP_BOOTSTRAP_ADMIN_PASSWORD', $password);
		TestHelperEnvironment::setEnvironmentVariable('APP_BOOTSTRAP_ADMIN_LOCALE', 'en_US');
		TestHelperEnvironment::setEnvironmentVariable('APP_BOOTSTRAP_ADMIN_TIMEZONE', 'UTC');

		try {
			$seed = new SeedSkeletonBootstrap();
			$seed->run(new SeedContext('app', 'mandatory', DEPLOY_ROOT . 'app', false));

			$user = User::getUserByName($username);
			$this->assertIsArray($user);
			$this->assertSame(1, (int) $user['is_active']);

			$system_developer_role_id = (int) DbHelper::selectOneColumn('roles_tree', [
				'role' => 'system_developer',
			], '', 'node_id');
			$system_admin_role_id = (int) DbHelper::selectOneColumn('roles_tree', [
				'role' => 'system_administrator',
			], '', 'node_id');
				$this->assertGreaterThan(0, $system_developer_role_id);
				$this->assertGreaterThan(0, $system_admin_role_id);
				$this->assertTrue(Roles::checkUserIsAssigned($system_developer_role_id, (int) $user['user_id']));
				$this->assertTrue(Roles::checkUserIsAssigned($system_admin_role_id, (int) $user['user_id']));
				$everyone_id = (int) DbHelper::selectOneColumn('usergroups_tree', ['title' => 'Everyone'], '', 'node_id');
				$logged_in_users_id = (int) DbHelper::selectOneColumn('usergroups_tree', ['title' => 'Logged in users'], '', 'node_id');
				$this->assertGreaterThan(0, $everyone_id);
				$this->assertGreaterThan(0, $logged_in_users_id);
				$this->assertGreaterThan(0, (int) DbHelper::selectOneColumn('roles_tree', ['role' => 'acl_viewer'], '', 'node_id'));

			$homepage = ResourceTreeHandler::getResourceTreeEntryData('/', 'index.html', Config::APP_DOMAIN_CONTEXT->value());
			$this->assertIsArray($homepage);
				$homepage_acl = DbHelper::selectOne('resource_acl', [
					'resource_id' => (int) $homepage['node_id'],
					'subject_type' => 'usergroup',
					'subject_id' => $everyone_id,
				], '', 'allow_view');
			$this->assertSame(1, (int) ($homepage_acl['allow_view'] ?? 0));
			$homepage_connection_id = Widget::getWidgetConnectionId((int) $homepage['node_id'], 'content', WidgetList::PLAINHTML);
			$this->assertIsInt($homepage_connection_id);
			$homepage_settings = PlainHtml::getSettings($homepage_connection_id);
			$this->assertStringContainsString('Radaptor App', (string) ($homepage_settings['content'] ?? ''));

			$login_page = ResourceTreeHandler::getResourceTreeEntryData('/', 'login.html', Config::APP_DOMAIN_CONTEXT->value());
			$this->assertIsArray($login_page);
				$login_acl = DbHelper::selectOne('resource_acl', [
					'resource_id' => (int) $login_page['node_id'],
					'subject_type' => 'usergroup',
					'subject_id' => $everyone_id,
				], '', 'allow_view');
			$this->assertSame(1, (int) ($login_acl['allow_view'] ?? 0));
			$form_connection_id = Widget::getWidgetConnectionId((int) $login_page['node_id'], 'content', WidgetList::FORM);
			$this->assertIsInt($form_connection_id);
			$form_attributes = AttributeHandler::getAttributes(
				new AttributeResourceIdentifier(ResourceNames::WIDGET_CONNECTION, (string) $form_connection_id)
			);
			$this->assertSame(FormList::USERLOGIN, $form_attributes['form_id'] ?? null);

			foreach ([
				'/admin/users/' => WidgetList::USERLIST,
				'/admin/usergroups/' => WidgetList::USERGROUPLIST,
				'/admin/roles/' => WidgetList::ROLELIST,
				'/admin/resources/' => WidgetList::RESOURCETREE,
				'/admin/components/adminmenu/' => WidgetList::ADMINMENU,
			] as $path => $widget_name) {
				$page = ResourceTreeHandler::getResourceTreeEntryData($path, 'index.html', Config::APP_DOMAIN_CONTEXT->value());
				$this->assertIsArray($page, "Expected autogenerated page for {$path}");
				$this->assertIsInt(Widget::getWidgetConnectionId((int) $page['node_id'], 'content', $widget_name));
			}
		} finally {
			TestHelperEnvironment::revertEnvironmentVariable('APP_BOOTSTRAP_ADMIN_TIMEZONE');
			TestHelperEnvironment::revertEnvironmentVariable('APP_BOOTSTRAP_ADMIN_LOCALE');
			TestHelperEnvironment::revertEnvironmentVariable('APP_BOOTSTRAP_ADMIN_PASSWORD');
			TestHelperEnvironment::revertEnvironmentVariable('APP_BOOTSTRAP_ADMIN_USERNAME');
		}
	}
}
